name: Build APK

on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем файлы
        uses: actions/checkout@v4

      - name: Распаковываем ZIP
        run: unzip ZeroGram.zip

      - name: Устанавливаем Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Чиним ошибки кода и собираем APK
        run: |
          DIR=$(dirname $(find . -name "settings.gradle" | head -1))
          cd "$DIR"

          # 1. Лечим ошибку с репозиториями (заменяем строгий запрет на мягкое правило)
          sed -i 's/FAIL_ON_PROJECT_REPOS/PREFER_SETTINGS/g' settings.gradle

          # 2. Скачиваем оригинальный запускатор, чтобы версия точно была 8.5
          wget -qO gradlew https://raw.githubusercontent.com/gradle/gradle/master/gradlew
          chmod +x gradlew

          # 3. Собираем APK
          ./gradlew assembleDebug

      - name: Сохраняем готовый APK
        uses: actions/upload-artifact@v4
        with:
          name: ZeroGram-apk
          path: '**/*.apk'
